config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/filtre', to: 'doctors#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :doctors, only: [:index, :show] do
    resources :favorites, only: [:create]
    resources :recommendations, only: [:new, :create]
  end
  resources :favorites, only: [:destroy]

  resources :profiles, only: [:show, :index] do
    resources :friendships, only: [:create]
  end
  resources :friendships, only: [:destroy]
  resources :invites, only: [:new, :create]

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = User.where.not(id: current_user.id).sort_by { |user| current_user.friends.pluck(:id).include?(user.id) ? 0 : 1 }
    if params.dig(:search)
      @profiles = @profiles.where(username: params.dig(:search, :username))
    end
  end

  def show
    @profile = User.find(params[:id])
    @friendship = current_user.friendships.find_by(friend_id: params[:id])
  end
end

app/views/profiles/index.html.erb
<%# Searchbar %>
<div class="ginny-show">
  <div class=" container px-4 pagination justify-content-center">
    <%= simple_form_for :search, url: profiles_path, method: :get, data: { controller: "search-form" } do |f| %>
      <div class="row">
        <div class="col pt-3 align-self-enter">
          <%= f.input :username,
            input_html: { value:  params.dig(:search, :username) },
            class: "form-control",
            placeholder: "Rechercher un.e ami.e ou membre",
            label: false
          %>
        </div>
      </div>
      <% end %>
  </div>
<%# Friend list %>
  <div class="container ginny-show px-2">
    <div class="user-profil-list">
      <% @profiles.each do |profile| %>
      <div class= "user-profil-card">
        <% if profile.photo.attached?%>
          <%= cl_image_tag profile.photo.key, class: "avatar-xxl mb-3", width: 200 %>
        <% end %>
        <h2 class="profil-username"><%= link_to "#{profile.username }", profile_path(profile) %>
        </h2>
        <p><%= pluralize(profile.favorites.count, "praticien.ne favori", "praticien.nes favoris") %>
        </p>
        <%# <% unless profile == current_user %>


        <div class="profile-button">
       <% if current_user.follow(profile) %>
            <div class="follow-button align-content-center">
              <%= link_to "Abonné.e", friendship_path(current_user.follow(profile)), method: :delete %>
            </div>
          <% else %>
            <div class="unfollow-button align-content-center">
              <%= link_to "S'abonner", profile_friendships_path(profile), method: :post %>
            </div>
          <% end %>
      </div>


      </div>
      <% end %>
    </div>
    <div class='d-flex justify-content-center p-3'>
      <%= link_to "Inviter un.e ami.e", new_invite_path, class: "button-secondary py-2", id:"add-friend-button" %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class=" ginny-show profile-show">
<%# Avatar %>

  <div class="profil-info">
    <div class="profil-text">
      <h2><%= @profile.username %></h2>
      <%# <p><%= pluralize(@profile.friendships.count, 'ami.e', 'ami.e.s')</p>%>
      <% unless @profile == current_user %>
      <div class="profile-button">
       <% if current_user.follow(@profile) %>
            <div class="follow-button align-content-center">
              <%= link_to "Abonné.e", friendship_path(current_user.follow(@profile)), method: :delete %>
            </div>
          <% else %>
            <div class="unfollow-button align-content-center">
              <%= link_to "S'abonner", profile_friendships_path(@profile), method: :post %>
            </div>
          <% end %>
      </div>
      <% end %>
    </div>

    <div class="profil-pic">
      <% if @profile.photo.attached?%>
        <%= cl_image_tag @profile.photo.key, class: "avatar-xxl mb-3", width: 200 %>
      <% end %>
    </div>
  </div>






  <h3>Soignant.e.s en favoris</h3>
  <div class="doctor-list">
    <% @profile.favorites.includes(:doctor).each do |favorite| %>
    <div class='box-bordered'>
      <div class ='doctor-card'>
        <div class="doctor-card-text">
        <h4>
          <%= link_to "#{favorite.doctor.first_name.capitalize} #{favorite.doctor.last_name.capitalize}", doctor_path(favorite.doctor) %>
        </h4>
        <p><%= favorite.doctor.street %></p>
        <p><%= favorite.doctor.city %></p>
        </div>
        <div class="doctor-card-tag">
          <div class="tag <%=favorite.doctor.profession%> p-2">
            <%= favorite.doctor.profession.capitalize %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>