config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/filtre', to: 'doctors#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :doctors, only: [:index, :show] do
    resources :favorites, only: [:create]
    resources :recommendations, only: [:new, :create]
  end
  resources :favorites, only: [:destroy]

  resources :profiles, only: [:show, :index] do
    resources :friendships, only: [:create]
  end
  resources :friendships, only: [:destroy]
  resources :invites, only: [:new, :create]

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/views/shared/_dashboard.html.erb
<div id='dashboard' class='hidden'>

    <div class="dashboard-infos">
    <% if user_signed_in? %>
      <%# <% if current_user.photo.attached?%>
        <%# <%= cl_image_tag current_user.photo.key, class: "avatar-xxl mb-3", width: 200 %>
      <%# <% end %>
      <div class="dashboard-user-card">
        <h2><%= current_user.username.upcase %></h2>
        <p><%= pluralize(current_user.friendships.count, 'ami.e', 'ami.e.s')%></p>
        <%# <%= current_user.recommendations.count%>
        <p><%= pluralize(current_user.recommendations.count, 'recommendation donnée', 'recommendations données') %></p><br>
      </div>
    </div>


    <h3 >Soignant.e.s en favoris</h3>
    <div id="favorites-container">
      <% current_user.favorites.includes(:doctor).each do |favorite| %>
        <%= render 'shared/dashboard_favorite', favorite: favorite %>
      <% end %>
    </div>
    <hr>

    <%# <p><%= current_user.doctors</p> formule ok quand on aura fav doctors%>
  <div class="dashboard-actions d-flex flex-column align-items-end justify-content-end ">
      <%= link_to 'Modification', edit_user_registration_path%><br>
      <%= link_to "Déconnexion", destroy_user_session_path, remote: true, method: :delete %>
    <% else %>
      <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_dashboard_favorite.html.erb
<ul class="dashboard-doctor-card"  data-favorite-id="<%= favorite.id %>">
  <div>
    <li >
      <h4><%= "#{favorite.doctor.first_name.capitalize} #{favorite.doctor.last_name.capitalize}" %></h4>
    </li>
    <li >
      <p class="tag <%=favorite.doctor.profession%> "><%= favorite.doctor.profession %></p>
    </li>
  </div>
  <li class= "delete smaller-text light-grey-color">
    <%= link_to 'x', favorite_path(favorite), method: :delete %>
  </li>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if params[:flash_notice] %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= params[:flash_notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <li class="nav-item active"> %>
  <%#= link_to "Home", "#", class: "nav-link" %>
<%# </li> %>
<%# <li class="nav-item">
  <a href="#" data-toggle="modal" data-target="#exampleModal" class="nav-link">
    <i class="fas fa-plus-circle reco-button"></i>
  </a>
</li> %>
<div id="footer" class="d-flex align-items-center justify-content-between position-fixed w-100" style="z-index: 100; bottom: 0; background-color: #F7F1ED;">

  <%= link_to doctors_path, class: "footer-link #{"active-footer-link" if (current_page?(doctors_path) && params[:search].nil?) ||
  (action_name == 'show' && controller_name == 'doctors' && @backlink == 'home') }" do %>
    <i class="fas fa-home"></i>
  <% end %>

  <a href="#" data-toggle="modal" class=footer-link data-target="#recommendationModal" class="nav-link p-0">
    <i class="fas fa-plus-circle"></i>
  </a>

  <%= link_to search_path, class: "footer-link #{"active-footer-link" if current_page?(search_path) ||
  (action_name == 'show' && controller_name == 'doctors' && @backlink == 'filtered') ||
  (current_page?(doctors_path) && params[:search])}" do %>
    <i class="fas fa-search"></i>
  <% end %>

  <%= link_to "", class: "footer-link" do %>
    <i class="far fa-file-alt" style="font-size: 30px; color: #470700;"></i>
  <% end %>

  <%= link_to profiles_path, class: "footer-link #{"active-footer-link" if current_page?(profiles_path)}" do %>
    <i class="fas fa-users"></i>
  <% end %>

</div>

  <%# <%= link_to "<i class='fas fa-search' style='font-size: 30px; color: 470700;'".html_safe, search_path %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to doctors_path, class: "navbar-brand " do %>
   <%= image_tag 'Ginny_logo.png' %>
  <% end %>

  <% if user_signed_in? %>
    <div class="nav-item dropdown" id="navbar-avatar">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "avatar", id: "navbarDropdown"%>
      <% else %>
        <%= image_tag 'avatar-par-defaut.jpg', class: "avatar", id: "navbarDropdown" %>
      <% end %>
    </div>
  <% else %>
<div class="nav-item">
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    </div>
  <% end %>
</div>

<%# <li class="nav-item active"> %>
  <%#= link_to "Home", "#", class: "nav-link" %>
<%# </li> %>
<%# <li class="nav-item">
  <a href="#" data-toggle="modal" data-target="#exampleModal" class="nav-link">
    <i class="fas fa-plus-circle reco-button"></i>
  </a>
</li> %>

<%#
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <%# <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto"> %>
      <%# if user_signed_in? %>
        <%# <li class="nav-item active"> %>
          <%#= link_to "Home", "#", class: "nav-link" %>
        <%# </li> %>
        <%# <li class="nav-item">
          <a href="#" data-toggle="modal" data-target="#exampleModal" class="nav-link">
            <i class="fas fa-plus-circle reco-button"></i>
          </a>
        </li>
        <li class="nav-item dropdown"> %>
          <%# if current_user.photo.attached? %>
            <%#= cl_image_tag current_user.photo.key, class: "avatar", id: "navbarDropdown"%>
          <%# else %>
            <%#= image_tag 'avatar-par-defaut.jpg', class: "avatar", id: "navbarDropdown" %>
          <%# end %>
          <%# </div> %>
        <%# </li> %>
      <%# else %>
        <%# <li class="nav-item"> %>
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <%# </li> %>
      <%# end %>
    <%# </ul> %>
  <%# </div> %>

app/views/shared/_recommendation.html.erb
<div class="modal fade" id="recommendationModal" tabindex="-1" role="dialog" aria-labelledby="recommendationModal" aria-hidden="true" data-controller="modal">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="recommendationModal">Ajouter une recommandation</h4>
      </div>
      <div class="modal-body px-4">
        <p data-modal-target="message">Merci de n’ajouter une recommandation de soignant.e que si tu l’as toi-même consulté.e et que tu souhaites le recommander à tes amis.
          <br>Autrement, tu peux le mettre en favoris.
        </p>

        <div class="d-none" data-modal-target="searchForm">
          <%= simple_form_for :search, url: doctors_path, method: :get, data: { controller: "search-form" } do |f| %>

            <div class="row d-flex justify-content-center">
              <div class="align-self-enter d-flex">
                <%= f.input :name_or_specialty,
                  input_html: { value:  params.dig(:search, :name_or_specialty) },
                  class: "form-control",
                  placeholder: "Jean Benamour, IVG",
                  label: "<i class='fas fa-search text-primary pin'></i>".html_safe,
                  required: false
                %>
              </div>
            </div>

            <div class="d-flex justify-content-center">

              <%= f.submit :Chercher, class: "button-main mb-4" %>
            </div>

          <% end %>
        </div>

      </div>
      <div class="modal-footer p-4" data-modal-target="footer">
        <div class="d-flex align-items-center">
          <input class="p-3" type="checkbox" id="opt-in" data-modal-target="checkbox">
          <label class="p-3" for="opt-in" data-modal-target="label">Oui, je recommande un.e soignant.e que j'ai consulté.e</label>
        </div>
        <div class="button-main" data-action="click->modal#change">Suivant</div>
        <div class="d-none">
          <%= link_to 'Suivant', search_path, data: { modal_target: 'nextButton' } %>
        </div>
      </div>
    </div>
  </div>
</div>