config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/search', to: 'pages#search'
  get '/filtre', to: 'doctors#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :doctors, only: [:index, :show] do
    resources :favorites, only: [:create]
    resources :recommendations, only: [:new, :create]
  end
  resources :favorites, only: [:destroy]

  resources :profiles, only: [:show, :index] do
    resources :friendships, only: [:create]
  end
  resources :friendships, only: [:destroy]
  resources :invites, only: [:new, :create]

  get 'dashboard', to: 'pages#dashboard', as: :dashboard
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :recommendations
  has_many :favorites
  has_many :tags, through: :recommendations
  has_many :badges, through: :recommendations
  validates :first_name, :last_name, :profession, :gender, presence: true

  reverse_geocoded_by :latitude, :longitude
  # after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_specialty,
    against: [
      [:last_name, "A"],
      :first_name,
      :specialty
    ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def self.professions
    pluck(:profession).uniq
  end

  def self.genders
    pluck(:gender).uniq
  end

  def self.conventions
    pluck(:convention).uniq
  end

  def badges
    recommendations.map do |reco|
      reco.badges
    end.flatten
  end

  def labels
    recommendations.map do |reco|
      reco.labels
    end.flatten
  end

  def group_badges
    badges.group_by(&:name)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # before_action :set_doctor, only: :edit

  def index

    @doctors = Doctor.near('Paris', 10000)

    if params.dig(:search, :address).present?
      @doctors = @doctors.near(params.dig(:search, :address), 10)
    end

    if params.dig(:search, :name_or_specialty).present?
      @doctors = @doctors.search_by_name_and_specialty(params.dig(:search, :name_or_specialty))
    end

    # if params.dig(:search, :specialty).present?
    #  @doctors = @doctors.where(specialty: params.dig(:search, :specialty))
    # end

    if params.dig(:search, :gender)&.last.present?
      @doctors = @doctors.where(gender: params.dig(:search, :gender))
    end

    if params.dig(:search, :profession)&.last.present?
      @doctors = @doctors.where(profession: params.dig(:search, :profession))
    end

    if params.dig(:search, :convention)&.last.present?
      @doctors = @doctors.where(convention: params.dig(:search, :convention))
    end

    if params.dig(:search, :tags)&.last.present? && params.dig(:search, :tags).reject(&:empty?).present?
      @doctors = @doctors.joins(:tags).where(tags: {name: params[:search][:tags].reject(&:empty?)})
    end

    if params.dig(:search, :badges)&.last.present? && params.dig(:search, :badges).reject(&:empty?).present?
      @doctors = @doctors.joins(:badges).where(badges: {picto: params[:search][:badges].reject(&:empty?)})
    end

    @markers = @doctors.map do |doctor|
      case doctor.profession
      when "sage-femme"
        icon = "sage-femme-w-icon"
      when "généraliste"
        icon = "generaliste-m-icon" if doctor.gender == "Homme"
        icon = "generaliste-w-icon" if doctor.gender == "Femme"
      when "gynécologue"
        icon = "gyneco-m-icon" if doctor.gender == "Homme"
        icon = "gyneco-w-icon" if doctor.gender == "Femme"
      end
      {
        latitude: doctor.latitude,
        longitude: doctor.longitude,
        icon: icon,
        info_window: render_to_string(partial: "marker_window", locals: { doctor: doctor })
      }
    end
  end

  def show
    @doctor = Doctor.find(params[:id])
    @backlink = params[:backlink]
    # @favorite = Favorite.find(params[:id])
    @friends = current_user.friends
    @recommendations = @friends.select{|friend| friend.recommended_doctor?(@doctor)}
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end
end

app/views/doctors/_filter.html.erb
<%= form_tag doctors_path, method: :get do %>
  <%= text_field_tag :speciality,
    params[:speciality],
    class: "form-control",
    placeholder: "La spécialité de mon praticien.ne"
  %>

  <%= text_field_tag :gender,
    params[:gender],
    class: "form-control",
    placeholder: "Le genre de mon praticien.ne"
  %>

   <%= text_field_tag :profession,
    params[:profession],
    class: "form-control",
    placeholder: "La profession de mon praticien.ne"
  %>

 <%= text_field_tag :convention,
    params[:convention],
    class: "form-control",
    placeholder: "La convention de mon praticien.ne"
  %>

  <%#= select_tag "tag", options_from_collection_for_select(Tag.all, "id", "name") %>
  <%#= select_tag "badge", options_from_collection_for_select(Badge.all, "id", "picto") %>

  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/doctors/_marker_window.html.erb
<div class="marker-window">
  <h4> <%= link_to " #{doctor.first_name.capitalize} #{doctor.last_name.capitalize}" , doctor_path(doctor)  %> </h4>
  <p class="street"><%= doctor.street %></p>
  <p class="city"><%= doctor.city %></p>
</div>

app/views/doctors/index.html.erb
<div class="map-container">
  <div id="map" class="map"
      style="width: 100%; height: 220px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="doctor-list">
  <% @doctors.uniq.each do |doctor| %>
    <div class='box-bordered'>
      <div class ='doctor-card'>
        <div class="doctor-card-text">
          <h4>
            <%= link_to "#{doctor.first_name.capitalize} #{doctor.last_name.capitalize}", doctor_path(doctor, backlink: params[:search].nil? ? 'home' : 'filtered'), :class => "stretched-link" %>
          </h4>
          <p><%= "#{doctor.street}" %></p>
          <p><%= "#{doctor.city}" %></p>
        </div>
        <div class="doctor-card-tag">
          <div class='tag p-2 <%=doctor.profession%>' >
            <%= "#{doctor.profession.capitalize}" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/doctors/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@doctor.first_name} #{@doctor.last_name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @doctor.profession %>


  <div class='box-bordered'>
    <div class ='doctor-card pb-4'>
      <div class="doctor-card-text">
        <h4><%= "#{@doctor.first_name.capitalize} #{@doctor.last_name.capitalize}" %></h4>
        <p><%= "#{@doctor.street}" %></p>
        <p><%= "#{@doctor.city}" %></p>
      </div>
      <div class="doctor-card-tag"
           data-controller="favorite"
           data-favorite-doctor-value="<%= @doctor.id %>"
           <%# data-favorite-favorite-value="<%= @doctor.favorites.ids %>" %>
          <div data-favorite-target="heart">
            <% if current_user.favorite_doctor?(@doctor) %>
              <i class="fas fa-heart mb-2" data-action="click->favorite#unfavorite" data-id="<%= current_user.favorite(@doctor)&.id %>"></i>
            <% else %>
               <i class="far fa-heart mb-2" data-action="click->favorite#favorite"></i>
            <% end %>
          </div>
        <%# end %>
        <div class='tag p-2 <%=@doctor.profession%>' >
          <%= "#{@doctor.profession.capitalize}" %>
        </div>
      </div>
    </div>
  </div>


  <div class="box-bordered custom-padding-ginny">
    <h4>Tags</h4>
    <div class="tag-list">
      <% @doctor.tags.uniq.each do |tag| %>
        <div class="tag p-2 mx-2 <%= tag.name %>">
          <p><%= tag.name %></p>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center pt-4">
      <%= link_to "Attribuer un tag", new_doctor_recommendation_path(@doctor), :class => "text-secondary" %>
    </div>
  </div>


  <div class="box-bordered custom-padding-ginny">
    <h4>Badges de la communauté</h4>
    <div class="badge-list">
      <% @doctor.group_badges.each do |key, value| %>
        <div class="badge-card">
          <div class="my-badge">
            <%= image_tag "badges/#{key}.jpg", size: 60 %>
            <div class="counter">
              <%= value.size %>
            </div>
          </div>
          <p><%= key.capitalize %></p>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center pt-4">
      <%= link_to "Attribuer un badge", new_doctor_recommendation_path(@doctor), :class => "text-secondary" %>
    </div>
  </div>

  <% if @recommendations.any? %>
    <div class="box-bordered custom-padding-ginny">
      <h4>Recommandé par</h4>
      <div class="badge-list">
        <div class="badge-card">
          <% @recommendations.each do |user|%>
            <% if user.photo.attached?%>
              <%= cl_image_tag user.photo.key, class: "avatar-xxl mb-3", width: 200 %>
              <p><%= link_to "#{user.username }", profile_path(user) %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="box-bordered custom-padding-ginny">
    <h4> Tarifs et remboursement</h4>
    <div class="pricing-info py-3">
      <p>Cout moyen: <%= "#{@doctor.average_number}" %> €</p>
      <p><%= @doctor.carte_vital %></p>
      <p>Conventionné <%= "#{@doctor.convention}" %></p>
    </div>
  </div>
</div>